services:
  - type: web
    name: mboa-command-api
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.0.0
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.hpffonuyhyoirzgmsigb:Auguste%40ictu2021@aws-0-eu-west-1.pooler.supabase.com:5432/postgres
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        sync: false
